# Generated by Django 5.2.8 on 2025-11-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(help_text='Main heading for the pricing section', max_length=200)),
                ('section_subtitle', models.CharField(help_text='Bold or slogan text', max_length=200)),
                ('section_paragraph', models.TextField(help_text='Paragraph / description text')),
            ],
        ),
    ]
