# Generated by Django 5.2.8 on 2025-11-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_pricingsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingplan',
            name='price',
            field=models.CharField(max_length=8),
        ),
    ]
