# Generated by Django 5.2.8 on 2025-11-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_pricingplan_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='link_button',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='price',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='pricingsection',
            name='section_title',
            field=models.CharField(blank=True, default='', help_text='Main heading for the pricing section', max_length=200),
        ),
    ]
