# Generated by Django 5.2.8 on 2025-11-10 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_pricingplan_link_button_alter_pricingplan_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feature',
            new_name='PricingFeature',
        ),
    ]
