# Generated by Django 5.2.8 on 2025-11-10 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_feature_pricingfeature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricingplan',
            options={'verbose_name': 'Pricing Plan', 'verbose_name_plural': 'Pricing Plans'},
        ),
        migrations.AlterModelOptions(
            name='pricingsection',
            options={'verbose_name': 'Pricing Section', 'verbose_name_plural': 'Pricing Sections'},
        ),
    ]
